# Generated by Django 4.2.7 on 2023-12-04 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yelp_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                ("yelp_url", models.URLField()),
                ("categories", models.CharField(max_length=255)),
                ("rating", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("distance", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
