# Generated by Django 4.2.7 on 2023-12-05 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_alter_savedrestaurant_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrestaurant",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="savedrestaurant",
            name="longitude",
        ),
    ]
