# Generated by Django 4.2.7 on 2023-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0003_remove_savedrestaurant_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrestaurant",
            name="distance",
        ),
    ]
